<!DOCTYPE html>
<!-- saved from url=(0022)https://r-rp.ru/forbes -->
<html lang="ru"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		
        <meta name="csrf-param" content="_csrf">
<meta name="csrf-token" content="mJt2PXqyssik0jHqVdYFoQPq5xIwBkX3P61Vi7QjHUKs2DhrD_3WiemBe5kDgnXMR4zUVnN0Na1P5QK-9kJ7LA==">
        <meta name="viewport" content="width=device-width,initial-scale=1">
		<title>RADMIR Forbes</title>
		<link href="./RADMIR Forbes_files/style.min.css" rel="stylesheet">
	</head>
	<body>
		        <style>.navbar__wrap{padding: 0 10px}</style>
        <div class="navbar">
            <div class="navbar__wrap">
                <div class="navbar__logo">
                <div class="logotype logotype_navbar">
                        <img class="logotype__image" src="./RADMIR Forbes_files/logo.png" alt="CRMP | Radmir RolePlay">
                        <div class="logotype__name">Radmir</div>
                        <div class="logotype__genre">Roleplay</div>
                    </div>
                </div>
                <button class="navbar__toggle-button" onclick="document.getElementsByClassName(&#39;navbar__nav&#39;)[0].classList.toggle(&#39;opened&#39;)">
                    <svg><use xlink:href="/contests/icons.svg#bars"></use></svg>
                </button>
                </nav>
                <div class="navbar__buttons">
                    <a class="navbar__button navbar__button_vk" href="https://vk.com/radmircrmp" target="_blank"><svg><use xlink:href="/contests/icons.svg#vk"></use></svg></a>
                    <a class="navbar__button navbar__button_yt" target="_blank" href="https://www.youtube.com/kovalevskiy"><svg><use xlink:href="/contests/icons.svg#play"></use></svg></a>

                                            <div class="navbar__login-button">
                            <a class="btn btn_orange" href="https://r-rp.ru/profile">Личный кабинет</a>
                            <a class="navbar__button navbar__button_login" href="https://r-rp.ru/profile">
                                <svg>
                                    <use xlink:href="/contests/icons.svg#user"></use>
                                </svg>
                            </a>
                        </div>
                    
                </div>
            </div>
        </div>
			
        
<style>
    .rating-nav {
        grid-template-columns: repeat(16, 1fr);
        width: 1024px
    }

    .place__skin {
        background-size: auto 215px;
        background-repeat: no-repeat
    }

    @media (max-width: 992px) {
        .forbes-item:nth-child(1), .forbes-item:nth-child(2), .forbes-item:nth-child(3) {
            display: none
        }

        .rating-nav {
            width: 100%;
            grid-gap: 15px;
            grid-template-columns: repeat(5, 1fr);
        }
    }
</style>

<div class="logo"><img class="logo__img" src="./RADMIR Forbes_files/forbes__logo.png" alt="">
    <div class="logo__text">Список игроков</div>
</div>

    </div>
<div class="rating-description">Самые состоятельные игроки</div>
<div class="first-places">
    <div class="place">
    <div class="place__cup place__cup_2"></div>
    <div class="place__skin" style="background-image: url(&#39;http://f0592632.xsph.ru/photo/1.jpg&#39;)"></div>
    <div class="place__nickname"></div>
    <div class="place__value">0 млн</div>
    </div>
    <div class="place">
    <div class="place__cup place__cup_1"></div>
    <div class="place__skin" style="background-image: url(&#39;http://f0592632.xsph.ru/photo/1.jpg&#39;)"></div>
    <div class="place__nickname"></div>
    <div class="place__value">0 млн</div>
    </div>
    <div class="place">
    <div class="place__cup place__cup_3"></div>
    <div class="place__skin" style="background-image: url(&#39;http://f0592632.xsph.ru/photo/1.jpg&#39;)"></div>
    <div class="place__nickname"></div>
    <div class="place__value">0 млн</div>
    </div>
</div>
<div class="block">
    <div class="block__body">
        <style>.forbes-item:nth-child(1), .forbes-item:nth-child(2), .forbes-item:nth-child(3) {
            display: grid !important;
        }
        </style>
                <div class="forbes-item">
            <div class="forbes-item__position">1</div>
            <div class="forbes-item__nickname"></div>
            <div class="forbes-item__server">Сервер 9</div>
            <div class="forbes-item__value">0 млн</div>
        </div>
                <div class="forbes-item">
            <div class="forbes-item__position">2</div>
            <div class="forbes-item__nickname"></div>
            <div class="forbes-item__server">Сервер 5</div>
            <div class="forbes-item__value">0 млн</div>
        </div>
                <div class="forbes-item">
            <div class="forbes-item__position">3</div>
            <div class="forbes-item__nickname"></div>
            <div class="forbes-item__server">Сервер 4</div>
            <div class="forbes-item__value">0 млн</div>
        </div>
                <div class="forbes-item">
            <div class="forbes-item__position">4</div>
            <div class="forbes-item__nickname"></div>
            <div class="forbes-item__server">Сервер 4</div>
            <div class="forbes-item__value">0 млн</div>
        </div>
                <div class="forbes-item">
            <div class="forbes-item__position">5</div>
            <div class="forbes-item__nickname"></div>
            <div class="forbes-item__server">Сервер 13</div>
            <div class="forbes-item__value">0 млн</div>
        </div>
                <div class="forbes-item">
            <div class="forbes-item__position">6</div>
            <div class="forbes-item__nickname"></div>
            <div class="forbes-item__server">Сервер 2</div>
            <div class="forbes-item__value">0 млн</div>
        </div>
                <div class="forbes-item">
            <div class="forbes-item__position">7</div>
            <div class="forbes-item__nickname"></div>
            <div class="forbes-item__server">Сервер 7</div>
            <div class="forbes-item__value">0 млн</div>
        </div>
                <div class="forbes-item">
            <div class="forbes-item__position">8</div>
            <div class="forbes-item__nickname"></div>
            <div class="forbes-item__server">Сервер 4</div>
            <div class="forbes-item__value">0 млн</div>
        </div>
                <div class="forbes-item">
            <div class="forbes-item__position">9</div>
            <div class="forbes-item__nickname"></div>
            <div class="forbes-item__server">Сервер 3</div>
            <div class="forbes-item__value">0 млн</div>
        </div>
                <div class="forbes-item">
            <div class="forbes-item__position">10</div>
            <div class="forbes-item__nickname"></div>
            <div class="forbes-item__server">Сервер 8</div>
            <div class="forbes-item__value">0 млн</div>
        </div>
                <div class="forbes-item">
            <div class="forbes-item__position">11</div>
            <div class="forbes-item__nickname"></div>
            <div class="forbes-item__server">Сервер 9</div>
            <div class="forbes-item__value">0 млн</div>
        </div>
                <div class="forbes-item">
            <div class="forbes-item__position">12</div>
            <div class="forbes-item__nickname"></div>
            <div class="forbes-item__server">Сервер 11</div>
            <div class="forbes-item__value">0 млн</div>
        </div>
                <div class="forbes-item">
            <div class="forbes-item__position">13</div>
            <div class="forbes-item__nickname"></div>
            <div class="forbes-item__server">Сервер 5</div>
            <div class="forbes-item__value">0 млн</div>
        </div>
                <div class="forbes-item">
            <div class="forbes-item__position">14</div>
            <div class="forbes-item__nickname"></div>
            <div class="forbes-item__server">Сервер 11</div>
            <div class="forbes-item__value">0 млн</div>
        </div>
                <div class="forbes-item">
            <div class="forbes-item__position">15</div>
            <div class="forbes-item__nickname"></div>
            <div class="forbes-item__server">Сервер 1</div>
            <div class="forbes-item__value">0 млн</div>
        </div>
                <div class="forbes-item">
            <div class="forbes-item__position">16</div>
            <div class="forbes-item__nickname"></div>
            <div class="forbes-item__server">Сервер 10</div>
            <div class="forbes-item__value">0 млн</div>
        </div>
                <div class="forbes-item">
            <div class="forbes-item__position">17</div>
            <div class="forbes-item__nickname"></div>
            <div class="forbes-item__server">Сервер 14</div>
            <div class="forbes-item__value">0 млн</div>
        </div>
                <div class="forbes-item">
            <div class="forbes-item__position">18</div>
            <div class="forbes-item__nickname"></div>
            <div class="forbes-item__server">Сервер 8</div>
            <div class="forbes-item__value">0 млн</div>
        </div>
                <div class="forbes-item">
            <div class="forbes-item__position">19</div>
            <div class="forbes-item__nickname"></div>
            <div class="forbes-item__server">Сервер 3</div>
            <div class="forbes-item__value">0 млн</div>
        </div>
                <div class="forbes-item">
            <div class="forbes-item__position">20</div>
            <div class="forbes-item__nickname"></div>
            <div class="forbes-item__server">Сервер 3</div>
            <div class="forbes-item__value"> млн</div>
        </div>
                    </div>
</div>
			
	
</body></html>
